# Site settings
name: GRUB2 File Manager
description: >
  基于 GRUB 2 Lua 5.1 的文件管理器。
repository: a1ive/grub2-filemanager
avatar: https://github.com/a1ive/grub2-filemanager/raw/master/boot/grub/themes/slack/icons/dir.png

# Build settings
theme: jekyll-theme-midnight
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - NTBOOT.NT6
  - NTBOOT.PE1
  - wimboot
  - oscdimg.exe

# Theme settings
show_downloads: false
